// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PulseSystem.Infraestructure.Persistence;

#nullable disable

namespace PulseSystem.Infraestructure.Migrations
{
    [DbContext(typeof(PulseSystemContext))]
    partial class PulseSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PulseSystem.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ROLE");

                    b.HasKey("Id");

                    b.ToTable("EMPLOYEES", "RM558830");
                });

            modelBuilder.Entity("PulseSystem.Domain.Entities.Gateway", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("LastIP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("LAST_IP");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("VARCHAR2(17)")
                        .HasColumnName("MAC_ADDRESS");

                    b.Property<decimal>("MaxCapacity")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_CAPACITY");

                    b.Property<decimal>("MaxCoverageArea")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_COVERAGE_AREA");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("MODEL");

                    b.Property<long>("ParkingId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGISTER_DATE")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<decimal>("Status")
                        .HasColumnType("NUMBER")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("ParkingId");

                    b.ToTable("GATEWAYS", (string)null);
                });

            modelBuilder.Entity("PulseSystem.Domain.Entities.Parking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AvailableArea")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVAILABLE_AREA");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CAPACITY");

                    b.Property<string>("FloorPlan")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("FLOOR_PLAN");

                    b.Property<string>("MapPlan")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("MAP_PLAN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REGISTER_DATE")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("StructurePlan")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("STRUCTURE_PLAN");

                    b.HasKey("Id");

                    b.ToTable("PARKINGS", (string)null);
                });

            modelBuilder.Entity("PulseSystem.Domain.Entities.Zone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<decimal>("Length")
                        .HasColumnType("NUMBER")
                        .HasColumnName("LENGTH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<long>("ParkingId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<decimal>("Width")
                        .HasColumnType("NUMBER")
                        .HasColumnName("WIDTH");

                    b.HasKey("Id");

                    b.HasIndex("ParkingId");

                    b.ToTable("ZONES", (string)null);
                });

            modelBuilder.Entity("PulseSystem.Domain.Entities.Gateway", b =>
                {
                    b.HasOne("PulseSystem.Domain.Entities.Parking", "Parking")
                        .WithMany("Gateways")
                        .HasForeignKey("ParkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("PulseSystem.Domain.Entities.Parking", b =>
                {
                    b.OwnsOne("PulseSystem.Domain.Entities.Address", "Location", b1 =>
                        {
                            b1.Property<long>("ParkingId")
                                .HasColumnType("NUMBER(19)");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("NVARCHAR2(9)")
                                .HasColumnName("CEP");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("NVARCHAR2(100)")
                                .HasColumnName("CITY");

                            b1.Property<string>("Complement")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("NVARCHAR2(50)")
                                .HasColumnName("COMPLEMENT");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("NVARCHAR2(100)")
                                .HasColumnName("NEIGHBORHOOD");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("NVARCHAR2(50)")
                                .HasColumnName("STATE");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("NVARCHAR2(100)")
                                .HasColumnName("STREET");

                            b1.HasKey("ParkingId");

                            b1.ToTable("PARKINGS");

                            b1.WithOwner()
                                .HasForeignKey("ParkingId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("PulseSystem.Domain.Entities.Zone", b =>
                {
                    b.HasOne("PulseSystem.Domain.Entities.Parking", "Parking")
                        .WithMany("Zones")
                        .HasForeignKey("ParkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("PulseSystem.Domain.Entities.Parking", b =>
                {
                    b.Navigation("Gateways");

                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
